name: 'Write Version to File'
author: 'Brett Dorrans'
description: 'A GitHub Action that fetches the latest release tag within a repo and writes this to a file'
inputs:
  filename:
    description: 'The filename to write the version tag to'
    required: true
    default: '/.VERSION'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.filename }}
branding:
  icon: 'hash'
  color: 'orange'
